export const Types = {
  GET_COUNTRIES_LOADING: "GET_COUNTRIES_LOADING",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAIL: "GET_COUNTRIES_FAIL",
  GET_COUNTRY_LOADING: "GET_COUNTRY_LOADING",
  GET_COUNTRY_SUCCESS: "GET_COUNTRY_SUCCESS",
  GET_COUNTRY_FAIL: "GET_COUNTRY_FAIL",
};
